name: Auto merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  automerge:
    name: Auto merge
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        # Custom action for auto merging already available on marketplace
        uses: pascalgn/automerge-action@135f0bdb927d9807b5446f7ca9ecc2c51de03c4a
        # Perform the auto merge action only when the PR is raised by dependabot
        if: github.actor == 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACTIONS_TOKEN }}
          # By default, whenever dependabot raises a PR, it automatically assigns a label named "dependencies"
          # So, this action merges those PRs labelled "dependencies" only
          MERGE_LABELS: dependencies
          MERGE_METHOD: merge
